#ifndef TRICORE_TDEP_H
#define TRICORE_TDEP_H

#include "gdbarch.h"

/* Tricore register numbers.  */
enum
{
  TRICORE_D0_REGNUM,
  TRICORE_D1_REGNUM,
  TRICORE_D2_REGNUM,
  TRICORE_D3_REGNUM,
  TRICORE_D4_REGNUM,
  TRICORE_D5_REGNUM,
  TRICORE_D6_REGNUM,
  TRICORE_D7_REGNUM,
  TRICORE_D8_REGNUM,
  TRICORE_D9_REGNUM,
  TRICORE_D10_REGNUM,
  TRICORE_D11_REGNUM,
  TRICORE_D12_REGNUM,
  TRICORE_D13_REGNUM,
  TRICORE_D14_REGNUM,
  TRICORE_D15_REGNUM,
  TRICORE_A0_REGNUM,
  TRICORE_A1_REGNUM,
  TRICORE_A2_REGNUM,
  TRICORE_A3_REGNUM,
  TRICORE_A4_REGNUM,
  TRICORE_A5_REGNUM,
  TRICORE_A6_REGNUM,
  TRICORE_A7_REGNUM,
  TRICORE_A8_REGNUM,
  TRICORE_A9_REGNUM,
  TRICORE_A10_REGNUM,
  TRICORE_A11_REGNUM,
  TRICORE_A12_REGNUM,
  TRICORE_A13_REGNUM,
  TRICORE_A14_REGNUM,
  TRICORE_A15_REGNUM,
  TRICORE_LCX_REGNUM, 
  TRICORE_FCX_REGNUM, 
  TRICORE_PCX_REGNUM, 
  TRICORE_PSW_REGNUM, 
  TRICORE_PC_REGNUM, 
  TRICORE_ICR_REGNUM, 
  TRICORE_ISP_REGNUM, 
  TRICORE_BTV_REGNUM, 
  TRICORE_BIV_REGNUM, 
  TRICORE_SYSCON_REGNUM, 
  TRICORE_PMUCON0_REGNUM, 
  TRICORE_DMUCON_REGNUM, 
  TRICORE_NUM_REGS
};

enum
{
  TRICORE_E0_REGNUM,
  TRICORE_E2_REGNUM,
  TRICORE_E4_REGNUM,
  TRICORE_E6_REGNUM,
  TRICORE_E8_REGNUM,
  TRICORE_E10_REGNUM,
  TRICORE_E12_REGNUM,
  TRICORE_E14_REGNUM,
  TRICORE_P0_REGNUM,
  TRICORE_P2_REGNUM,
  TRICORE_P4_REGNUM,
  TRICORE_P6_REGNUM,
  TRICORE_P8_REGNUM,
  TRICORE_P10_REGNUM,
  TRICORE_P12_REGNUM,
  TRICORE_P14_REGNUM,
  TRICORE_PSEUDO_NUM
};

struct tricore_gdbarch_tdep : gdbarch_tdep_base
{
};

#endif